### ISSUE TITLE
Adding more constraints for FeatureProvider trait?

### ISSUE THREAD

**Issue by sheepduke** [open-feature/rust-sdk#12]
Hi folks,

I am trying to implement my own `FeatureProvider` that invokes an HTTP call to fetch the configurations. To avoid too many requests, I want to cache the result in my provider implementation.

The only trait bound of type `T` in the `resolution` function is `Clone`. However, any popular thread-safe cache solution requires the content to be `Send + Sync`. Of course, we can use `RwLock` to achieve it but it introduces extra performance penalty.

Considering the nature of "feature toggle" that the values should be "pure values", adding `Send + Sync` should not break anything.

What do you think?

**Comment by sheepduke** [comment]
Well, I think I can help maintain this project. 

What is the current situation of this project? Are the APIs stable? Where should I start?

**Comment by beeme1mr** [comment]
None of the APIs are considered stable at this point. It would be worth comparing the existing code against the [specification](https://github.com/open-feature/spec/tree/main/specification). You could also refer to stable SDKs like [Java](https://github.com/open-feature/java-sdk) and [Go](https://github.com/open-feature/go-sdk) for ideas on the implementation. However, the spec was written in a way that should allow for each language to "feel right" to a developer.

Personally, I'm inexperienced with Rust, but I can try and connect you with others if you run into any issues. Perhaps @AlexsJones could catch you up on where he left off.

**Comment by sheepduke** [comment]
> It would be worth comparing the existing code against the [specification](https://github.com/open-feature/spec/tree/main/specification). You could also refer to stable SDKs like [Java](https://github.com/open-feature/java-sdk) and [Go](https://github.com/open-feature/go-sdk) for ideas on the implementation. However, the spec was written in a way that should allow for each language to "feel right" to a developer.

I scanned through the code base and will probably check the spec next week. :-)

I saw an ongoing PR that intends to make the traits `async` writtin by Alexs. It would be nice if he could provide more context.

By the way, what is your preferred way of collaboration? Committing via PR or simply push main?

**Comment by beeme1mr** [comment]
Let's start with opening up PRs. I can then reference those contributions in a request to add you to the org. From there, we can make sure you have the permission you need. Thanks for your support. Having a stable Rust SDK will be great.

**Comment by sheepduke** [comment]
Closing with #15 merged.
