### ISSUE TITLE
[SDK] release-please

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/rust-sdk#4]
In order to keep our crate up to date we should be releasing automatically/via PR and producing released artifacts
This would mean that end-users to pin to a version rather than the main branch as per the current README guidelines

**Comment by toddbaert** [comment]
To any potential implementer, please take a look at the release please plugin config in the existing SDKs: [js](https://github.com/open-feature/js-sdk/blob/main/.github/workflows/release-please.yml), [java](https://github.com/open-feature/java-sdk/blob/main/.github/workflows/release.yml), [go](https://github.com/open-feature/go-sdk/blob/main/.github/workflows/release-please.yml).

**Comment by sheepduke** [comment]
Closing this because release-please has been set up and #32 has been merged.
