### ISSUE TITLE
[SDK] Implement API singleton

### ISSUE THREAD

**Issue by toddbaert** [open-feature/rust-sdk#6]
Currently, there's no means of getting a client without specifying a provider, or a means of setting the global provider instance.

See [1.1.1, 1.1.2, and 1.1.3](https://github.com/open-feature/spec/blob/main/specification/sections/01-flag-evaluation.md#11-api-initialization-and-configuration).

**Comment by AlexsJones** [comment]
This doesn't feel like a very rust idiom though. When would you want a client without a provider?
When would you use multiple clients that need the same provider but shared globally rather than by scope? 

This doesn't seem to advance the project, but more of an implementation detail

**Comment by toddbaert** [comment]
> When would you want a client without a provider?

It's not that you'd want a client without a provider, it's that there may be one globally configured provider that need not be supplied at the creation of every client. The global singleton is also the mechanism by which 3rd party libraries can add OpenFeature flags and first party users of that library can supply the provider for those flags. Vendor agnostic flags embedded in 3rd party libraries has been a goal since inception ([OTel has similar goals](https://opentelemetry.io/docs/concepts/instrumenting-library/)).

**Comment by sheepduke** [comment]
Closing with https://github.com/open-feature/rust-sdk/pull/15 merged.

**Comment by sheepduke** [comment]
Closing with #15 merged.
